[annotation.hpo]
file = "gene2hpo.txt"
mainKey = "entre-gene-id"
titleKey = ["HPO-Term-ID", "HPO-Term-NameCN"]
title = ["hpo", "hpo_cn"]

[annotation.REVEL]
file = "revel.lite.tsv.gz"
key = ["Stop", "Ref", "Call"]
keyIndex = [1, 2, 3]
title = ["REVEL_score"]
titleIndex = [4]

[annotation.GnomAD.MT]
file = "gnomad.genomes.v3.1.sites.chrM.reduced_annotations.tsv.db"
mainKey = "MTmut"
titleKey = ["AC_hom", "AC_het", "AF_hom", "AF_het", "AN"]
title = ["MT_AC_hom", "MT_AC_het", "MT_AF_hom", "MT_AF_het", "MT_AN"]

[annotation.Gene.spectrum]
file = "V4.3.1(2021Q1) 基因库-202100303-修正别名问题导致的PVS1基因list.xlsx.突变谱汇总.json.aes"
type = "json"
codeKey = "****"
titleKey = ["突变谱"]
title = ["突变频谱"]

[annotation.Gene.disease]
file = "全外疾病库2020.Q4-2021.2.5V1.xlsx.更新后全外背景库（5755疾病OMIMID，4372个基因）.json.aes"
type = "json"
codeKey = "****"
titleKey = [
    "Disease NameEN",
    "Disease NameCH",
    "Alternative Disease NameEN",
    "Location",
    "Gene/Locus",
    "Gene/Locus MIM number",
    "Inheritance",
    "GeneralizationEN",
    "GeneralizationCH",
    "SystemSort",
    "lab-翻译",
    "发病年龄",
    "imprinted gene/Expressed Allele",
    "Phenotype MIM number",
]
title = [
    "DiseaseNameEN",
    "DiseaseNameCH",
    "AliasEN",
    "Location",
    "Omim Gene",
    "Gene/Locus MIM number",
    "ModeInheritance",
    "GeneralizationEN",
    "GeneralizationCH",
    "SystemSort",
    "Lab-CH",
    "Onset age",
    "imprinted gene",
    "OMIM_Phenotype_ID",
]